/*
Name: Frank Zhen Yuan
Date: 8/3/2022
Class: ICS4UE-20, Mr. Williamson
 */

//Workaround of importing the (forms_rt.jar) module dependencies
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;


// Form inhering from JFrame. Because IntelliJ doesn't include it by default
public class AboutMe extends JFrame {
    // JFrame Elements list
    private JPanel mainPanel;
    private JLabel Name;
    private JLabel Subjects;
    private JLabel SubjectsL;
    private JLabel LastName;
    private JLabel LastNameL;
    private JLabel Color;
    private JLabel ColorL;
    private JLabel Music;
    private JLabel MusicL;
    private JLabel MusicGenre;
    private JLabel MusicGenreL;
    private JLabel School;
    private JLabel SchoolL;
    private JLabel NameL;

    // TITLE. Constructor accepting string representing the name of the app or frame.
    public AboutMe(String title) {
        super(title);

        //boiler plate codes

        //Program exit code
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setting content pane
        this.setContentPane(mainPanel);
        this.pack();
    }

    //Program main entry point
    public static void main(String[] args) {
        //Defining the title

        JFrame frame = new AboutMe("About Me!");
        //Setting JFrame visible for seeing it.

        frame.setVisible(true);
    }


    // Down below is the source code for the make up of the app, which uses

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 3, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 2, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        NameL = new JLabel();
        NameL.setEnabled(true);
        NameL.setForeground(new Color(-16743749));
        NameL.setText("Name: ");
        mainPanel.add(NameL, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SchoolL = new JLabel();
        SchoolL.setForeground(new Color(-4493819));
        SchoolL.setText("School:");
        mainPanel.add(SchoolL, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        School = new JLabel();
        School.setText("Jarvis Collegiate Institute");
        mainPanel.add(School, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MusicGenreL = new JLabel();
        MusicGenreL.setForeground(new Color(-4517229));
        MusicGenreL.setText("Favorite Music Genre:");
        mainPanel.add(MusicGenreL, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MusicGenre = new JLabel();
        MusicGenre.setText("1950s Jazz");
        mainPanel.add(MusicGenre, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MusicL = new JLabel();
        MusicL.setForeground(new Color(-4517632));
        MusicL.setText("Favorite Music:");
        mainPanel.add(MusicL, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Music = new JLabel();
        Music.setText("Mr. Sandman");
        mainPanel.add(Music, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ColorL = new JLabel();
        ColorL.setText("Favorite Color:");
        mainPanel.add(ColorL, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Color = new JLabel();
        Color.setText("White");
        mainPanel.add(Color, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LastNameL = new JLabel();
        LastNameL.setForeground(new Color(-16743749));
        LastNameL.setText("Last Name:");
        mainPanel.add(LastNameL, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LastName = new JLabel();
        LastName.setText("Yuan");
        mainPanel.add(LastName, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SubjectsL = new JLabel();
        SubjectsL.setForeground(new Color(-15353075));
        SubjectsL.setText("Favorite Class:");
        mainPanel.add(SubjectsL, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Subjects = new JLabel();
        Subjects.setText("\"all of them\"");
        mainPanel.add(Subjects, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Name = new JLabel();
        Name.setText("Frank Zhen");
        mainPanel.add(Name, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
